// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyAUDYHLdHCEF5zU_5sK5GnZq1vEW2D6Q',
    appId: '1:830616967064:web:f7d9fdc805a8858424fded',
    messagingSenderId: '830616967064',
    projectId: 'trailtales-mvp-56737',
    authDomain: 'trailtales-mvp-56737.firebaseapp.com',
    storageBucket: 'trailtales-mvp-56737.firebasestorage.app',
    measurementId: 'G-QKQ9M0VY27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2V-TKZ5TnhGmyGKKgnRZue48w-jIaizI',
    appId: '1:830616967064:android:ce9e14f6baba8df324fded',
    messagingSenderId: '830616967064',
    projectId: 'trailtales-mvp-56737',
    storageBucket: 'trailtales-mvp-56737.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNwRtEBV9_l0xlzrw43Sqk-4fAGHHUuic',
    appId: '1:830616967064:ios:f9633bfedf2815e424fded',
    messagingSenderId: '830616967064',
    projectId: 'trailtales-mvp-56737',
    storageBucket: 'trailtales-mvp-56737.firebasestorage.app',
    iosBundleId: 'com.example.trailtales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNwRtEBV9_l0xlzrw43Sqk-4fAGHHUuic',
    appId: '1:830616967064:ios:f9633bfedf2815e424fded',
    messagingSenderId: '830616967064',
    projectId: 'trailtales-mvp-56737',
    storageBucket: 'trailtales-mvp-56737.firebasestorage.app',
    iosBundleId: 'com.example.trailtales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyAUDYHLdHCEF5zU_5sK5GnZq1vEW2D6Q',
    appId: '1:830616967064:web:2465c14d5e3e663e24fded',
    messagingSenderId: '830616967064',
    projectId: 'trailtales-mvp-56737',
    authDomain: 'trailtales-mvp-56737.firebaseapp.com',
    storageBucket: 'trailtales-mvp-56737.firebasestorage.app',
    measurementId: 'G-207B9KJHZW',
  );
}
